name: Coverage
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: dschep/install-poetry-action@v1.3
      - name: Setup Environment
        run: |
          pip3 install --upgrade pip
          poetry install
      - name: Run Coverage
        run: |
          poetry run coverage run -m --omit=tests/* --source=. pytest tests/test_jinja.py
          poetry run coverage xml --omit=tests/* -i
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml 
          fail_ci_if_error: true
