# Prior to using CodeCov install the github app (https://github.com/apps/codecov)
# An account on codecov.io is also requried (https://bit.ly/2CIfXbv)
# CodeCov App: https://github.com/marketplace/codecov
# Checkout Action: https://github.com/marketplace/actions/checkout
# Python Action: https://github.com/marketplace/actions/setup-python
# Poetry Action: https://github.com/marketplace/actions/install-poetry-action
# Codecov Action: https://github.com/marketplace/actions/codecov

name: Coverage
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Setup Dependencies
        run: |
          pip3 install --upgrade pip
          poetry install
      - name: Run Coverage Reports
        run: |
          poetry run coverage run -m --omit=tests/* --source=. pytest tests/test_jinja.py
          poetry run coverage xml --omit=tests/* -i
      - name: Upload Coverage to Codecov  
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml 
          fail_ci_if_error: true
