# Checkout Action: https://github.com/marketplace/actions/checkout
# Python Action: https://github.com/marketplace/actions/setup-python
# Poetry Action: https://github.com/marketplace/actions/install-poetry-action

name: PyTests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Setup Dependencies
        run: |
          pip3 install --upgrade pip
          poetry install
      - name: Run PyTests
        run: |
          poetry run pytest tests
