name: Run Unit Tests
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: dschep/install-poetry-action@v1.3
      - name: Setup Environment
        run: |
          pip -m pip install --upgrade pip
          poetry install
      - name: Run PyTests
        run: |
          poetry run pytest tests
